language: php
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist
script:
  - phpunit --verbose tests/MockTest
#  - phpunit --verbose tests/SerializeTest

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
